[Nickname] # 现在没用
nickname = ""

[Lagrange_Server] # Lagrange连接的ws服务设置
host = "localhost" # Lagrange设定的主机地址
port = 8081        # Lagrange设定的端口
heartbeat = 50     # 与Lagrange设置的心跳相同（按秒计）

[MaiBot_Server] # 连接麦麦的ws服务设置
platform_name = "qq" # 标识adapter的名称（必填）
host = "localhost"   # 麦麦在.env文件中设置的主机地址，即HOST字段
port = 8000          # 麦麦在.env文件中设置的端口，即PORT字段

[Whitelist] # 白名单功能（未启用）（未实现）
group_list = []
private_list = []
enable_temp = false

[Debug]
level = "INFO" # 日志等级（DEBUG, INFO, WARNING, ERROR）
